theme = "catppuccin_latte"

[editor]
bufferline = "always"
line-number = "relative"
file-picker.hidden = false
soft-wrap.enable = true

[keys.normal]
C-s = ":write"
C-r = ":reload"

[keys.insert]
C-s = ":write"
