theme = "catppuccin_mocha"

[editor]
bufferline = "always"
line-number = "relative"
file-picker.hidden = false
soft-wrap.enable = true
atomic-save = false

[keys.normal]
C-s = ":write"
C-r = ":reload"
C-b = ":buffer-close"

[keys.insert]
C-s = ":write"
