[tools]
usage = "latest"

deno = "latest"
node = "lts"
"github:pnpm/pnpm" = "latest"
"npm:publint" = "latest"
"npm:knip" = "latest"
"npm:@mariozechner/pi-coding-agent" = "latest"

go = "latest"
"go:github.com/mr-karan/doggo/cmd/doggo" = "latest"
"go:github.com/charmbracelet/crush" = "latest"

"cargo:codebook-lsp" = "latest"
"cargo:jnv" = "latest"
"cargo:mergiraf" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
